name: ganache-cli CD

on:
  push:
    branches: [canary]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Git Identity
        run: |
          git config --global user.name 'ganache-test-bot'
          git config --global user.email 'david+ganache-test-bot@trufflesuite.com'
          git remote set-url origin https://ganache-test-bot:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install
        run: npm ci

      - name: Test
        run: npm test
        env:
          INFURA_KEY: ${{ secrets.INFURA_KEY }}

      - name: Build
        run: npm run build

      - name: Version
        # ${GITHUB_REF##*/} is the branch name
        run: $(npm bin)/lerna version prerelease --yes --exact --preid ${GITHUB_REF##*/}
        # TODO: require signed commits and tags via ` --sign-git-tag --sign-git-commit`

      - name: Update versions in npm-shrinkwrap
        run: $(npm bin)/lerna exec -- npm shrinkwrap

      # - name: Smoke test release
      # TODO: set up verdaccio to mock npm https://verdaccio.org/

      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: $(npm bin)/lerna publish from-git --yes --dist-tag ${GITHUB_REF##*/} --pre-dist-tag ${GITHUB_REF##*/}
